FROM node:20-slim

WORKDIR /app

# ✅ REQUIRED FOR PRISMA
RUN apt-get update -y \
    && apt-get install -y openssl \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build

CMD ["node", "dist/infrastructure/kafka/job.worker.js"]
